spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_example?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: _R0$!n#@_
    driver-class_name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

